name: CI/CD Pipeline

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies for AI models
      run: |
        pip install -r ai-models/requirements.txt

    - name: Install dependencies for API
      run: |
        pip install -r api/requirements.txt

    - name: Run unit tests
      run: |
        pytest tests/unit

    - name: Build Docker image
      run: |
        docker build -t your-docker-image:latest .

    - name: Push Docker image to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push your-docker-image:latest

    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          k8s/deployment.yaml
          k8s/service.yaml
          k8s/istio-gateway.yaml
